print("Welcome to Band Name Generator")
print("Let's create a unique band name based on some fun inputs.")
print()
front_name =input("What do you want to add in front of the name?\n")
name = input("What's your name?\n")
print()
print("Drumroll, please...")
print()
print(f"Congratulations! Your band name could be '{front_name} {name}' !")
print("Rock on!")